In [1]:
import math
from collections import defaultdict
import numpy as np

# Sudoku Solver

In [2]:
# Create a 9 by 9 grid

grid = [[0]*9]*9

In [3]:
# Helper function to print the sudoku grid

def print_grid(grid: list):
    for row in grid:
        print(row)


In [4]:
# Create the grid from set of strings 

grid_str = ["000260701","680070090","190004500","820100040","004602900","050003028","009300074","040050036","703018000"]

grid = [list(map(int,a)) for a in grid_str]


In [5]:
# Creating the grid datastructures
grid_str = ["000260701","680070090","190004500","820100040","004602900","050003028","009300074","040050036","703018000"]

grid = [list(map(int,a)) for a in grid_str]
grid = [list(map(int,a)) for a in grid_str]
grid = np.array(grid)
grid_dict = defaultdict(list)

In [6]:
grid

array([[0, 0, 0, 2, 6, 0, 7, 0, 1],
       [6, 8, 0, 0, 7, 0, 0, 9, 0],
       [1, 9, 0, 0, 0, 4, 5, 0, 0],
       [8, 2, 0, 1, 0, 0, 0, 4, 0],
       [0, 0, 4, 6, 0, 2, 9, 0, 0],
       [0, 5, 0, 0, 0, 3, 0, 2, 8],
       [0, 0, 9, 3, 0, 0, 0, 7, 4],
       [0, 4, 0, 0, 5, 0, 0, 3, 6],
       [7, 0, 3, 0, 1, 8, 0, 0, 0]])

# Helper Functions 

In [7]:
def find_superpositions(tuple_indices):
    i_row = tuple_indices[0]
    i_col = tuple_indices[1]
    
    superpositions = set(range(1,10))

    row_set = set(grid[i_row])
    superpositions = superpositions.difference(row_set)
    row_col = set(grid[:,i_col])
    superpositions = superpositions.difference(row_col)

    start_index_row = ((i_row//3)*3)
    start_index_col = ((i_col//3)*3)

    block_set = np.unique(grid[start_index_row:start_index_row+3,start_index_col:start_index_col+3])
    superpositions = superpositions.difference(block_set)

    return superpositions

In [8]:
def collapse_wave_function(grid_dict):
    for indices in grid_dict: 
        if type(grid_dict[indices])==set and len(grid_dict[indices])==1:
            grid_dict[indices] = list(grid_dict[indices])[0]
    return grid_dict


In [19]:
# Create grid from grid dict
def create_grid(grid,grid_dict):
    for (i_row,i_col),value in grid_dict.items():
        if isinstance(value,int) or isinstance(value,float):
            grid[i_row,i_col]=value
    
    return grid


In [22]:
grid

array([[4, 3, 5, 2, 6, 9, 7, 8, 1],
       [6, 8, 2, 5, 7, 1, 4, 9, 3],
       [1, 9, 7, 8, 3, 4, 5, 6, 2],
       [8, 2, 6, 1, 9, 5, 3, 4, 7],
       [3, 7, 4, 6, 8, 2, 9, 1, 5],
       [9, 5, 1, 7, 4, 3, 6, 2, 8],
       [5, 1, 9, 3, 2, 6, 8, 7, 4],
       [2, 4, 8, 9, 5, 7, 1, 3, 6],
       [7, 6, 3, 4, 1, 8, 2, 5, 9]])

In [27]:
grid_str = ["000260701","680070090","190004500","820100040","004602900","050003028","009300074","040050036","703018000"]

grid = [list(map(int,a)) for a in grid_str]
grid = [list(map(int,a)) for a in grid_str]
grid = np.array(grid)
grid_dict = defaultdict(list)

In [28]:
grid

array([[0, 0, 0, 2, 6, 0, 7, 0, 1],
       [6, 8, 0, 0, 7, 0, 0, 9, 0],
       [1, 9, 0, 0, 0, 4, 5, 0, 0],
       [8, 2, 0, 1, 0, 0, 0, 4, 0],
       [0, 0, 4, 6, 0, 2, 9, 0, 0],
       [0, 5, 0, 0, 0, 3, 0, 2, 8],
       [0, 0, 9, 3, 0, 0, 0, 7, 4],
       [0, 4, 0, 0, 5, 0, 0, 3, 6],
       [7, 0, 3, 0, 1, 8, 0, 0, 0]])

In [29]:
index__=0
while index__ < 5:
    print(f"Iteration-------------{index__}")        
    for i_row,row in enumerate(grid):
        for i_col,element in enumerate(row):
            if element!=0:
                grid_dict[(i_row,i_col)] = element
            else:
                grid_dict[(i_row,i_col)] = find_superpositions((i_row,i_col))

    grid_dict = collapse_wave_function(grid_dict)
    grid = create_grid(grid, grid_dict)
    print(grid)
    index__+=1

Iteration-------------0
[[0 3 5 2 6 0 7 8 1]
 [6 8 0 5 7 0 0 9 0]
 [1 9 0 8 0 4 5 0 0]
 [8 2 0 1 9 0 0 4 0]
 [3 0 4 6 8 2 9 0 0]
 [9 5 0 0 0 3 0 2 8]
 [0 0 9 3 2 6 0 7 4]
 [2 4 0 0 5 0 0 3 6]
 [7 6 3 0 1 8 2 5 0]]
Iteration-------------1
[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 0 9 0]
 [1 9 0 8 3 4 5 6 0]
 [8 2 0 1 9 0 0 4 0]
 [3 0 4 6 8 2 9 1 0]
 [9 5 0 0 4 3 0 2 8]
 [5 1 9 3 2 6 0 7 4]
 [2 4 0 0 5 0 0 3 6]
 [7 6 3 0 1 8 2 5 9]]
Iteration-------------2
[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 0 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 0 1 9 0 0 4 0]
 [3 7 4 6 8 2 9 1 0]
 [9 5 0 7 4 3 6 2 8]
 [5 1 9 3 2 6 8 7 4]
 [2 4 8 0 5 7 0 3 6]
 [7 6 3 4 1 8 2 5 9]]
Iteration-------------3
[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 4 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 6 1 9 5 3 4 0]
 [3 7 4 6 8 2 9 1 5]
 [9 5 1 7 4 3 6 2 8]
 [5 1 9 3 2 6 8 7 4]
 [2 4 8 9 5 7 1 3 6]
 [7 6 3 4 1 8 2 5 9]]
Iteration-------------4
[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 4 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 6 1 9 5 3 4 7]
 [3 7 4 6 8 2 9 1 5]
 [9 5 1 7 4 3 6